on:
  pull_request:
    branches:
      - main

jobs:
  run_unit_tests:
    runs-on: X4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - run: npm test

  run_linting:
    runs-on: X4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run lint

      - name: Verify package.json version matches version.ts (genversion --check-only)
        run: ./verify_version.sh

  run_compiler:
    runs-on: X4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run compile
